version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "34577"
      MYSQL_DATABASE: "bd_chazu"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: "${DOCKERHUB_USERNAME}/chazu-backend:latest"
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: "root"
      DB_PASSWORD: "34577"
      DB_NAME: "bd_chazu"
      ALEGRA_EMAIL: "tu_correo@ejemplo.com"
      ALEGRA_TOKEN: "tu_token_de_alegra"
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    # Usa wait-for-it para esperar a que MySQL esté listo antes de iniciar el backend
    command: sh -c "/wait-for-it.sh mysql:3306 -- node src/index.js"

  frontend:
    image: "${DOCKERHUB_USERNAME}/chazu-frontend:latest"
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
