name: Build and Test Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Backend Docker Image
        run: docker build -t chazu-backend -f Dockerfile .

      - name: Build Frontend Docker Image
        run: docker build -t chazu-frontend -f client/Dockerfile ./client

      - name: Run Backend Container and Test Endpoint
        run: |
          docker run --rm -d --name backend_test -p 5000:5000 chazu-backend
          # Espera unos segundos para que el servidor inicie
          sleep 10
          # Verifica que el endpoint raíz responda (ajusta la URL si es necesario)
          curl -f http://localhost:5000 || exit 1
          docker stop backend_test

      - name: (Opcional) Validar docker-compose
        run: docker-compose -f docker-compose.yml config
